### PR TITLE
Changed several xrange to range, as per Python 3 specifications, also…

### PR DESCRIPTION
**Pull request by cesposo**
… on line 149 of average_precision_calculator.py from list type to zip-type again as per Python 3 changes

### CODE REVIEW

**Comment by cesposo** [comment]
I signed it!

**Comment by LeegleechN** [comment]
Please add "from builtins import range" wherever it is used. This will make Python2's range function act the same as Python3's.

**Comment by cesposo** [comment]
Hi I accidentally added another pull request, but I have changed the file. If you want you can just close this one.

**Comment by LeegleechN** [comment]
Turns out this one was also needed.

**Pull request merged**
