### PR TITLE
Add config file to use GPUs

### PR DESCRIPTION
**Pull request by jingjinglong**
This config file can be used by the gcloud command to tell CloudML to use GPU resources.

### CODE REVIEW

**Comment by LeegleechN** [comment]
Please update the README.md to incorporate the config file.

**Comment by jingjinglong** [comment]
I have it in a separate pull request.  Is that sufficient?

**Comment by jingjinglong** [comment]
The other change to actually use the file: https://github.com/google/youtube-8m/pull/10

**Comment by LeegleechN** [comment]
OK, I'd merge this one, but in general it would be better to keep related concepts in the same pull request.

**Pull request merged**
